<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0-windows10.0.26100.0</TargetFramework>
    <TargetPlatformMinVersion>10.0.26100.0</TargetPlatformMinVersion>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <RootNamespace>Witness.Platform.Windows</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Witness.Core\Witness.Core.csproj" />
    <ProjectReference Include="..\Witness.Update\Witness.Update.csproj" />
  </ItemGroup>
</Project>
