<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>Witness.Update</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="NSec.Cryptography" />
    <PackageReference Include="Velopack" />
  </ItemGroup>
</Project>
