// Produces one key of each kind, for the app's test suite to read back.
//
// `docs/PHASE_8.md`: "Parity is a test, not a hope. Before the service issues a
// key to anyone, have it produce one key of each kind into a fixture file and
// add a test beside `LicenseIssuerToolTests` that reads them through the
// shipping `LicenseKey.verify`."
//
// Everything here is fixed — the seed, the identifiers, the timestamps — so the
// output is byte for byte reproducible and the committed fixture is a diff
// rather than a mystery. `ActivationServiceParityTests` verifies the committed
// file always, and regenerates it to catch drift whenever Node is on the
// machine.
//
//   node tools/parity-fixture.mjs            # rewrite Service/fixtures/parity.json
//   node tools/parity-fixture.mjs --out P    # write it somewhere else
//   node tools/parity-fixture.mjs --check    # fail if the committed file is stale

import { writeFileSync, readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { resolve } from "node:path";

import { issueToken } from "../src/token.js";
import { importSigningKey } from "../src/signing.js";
import { keypairFromSeed } from "../test/support/keys.mjs";

// Not a secret and never used for anything: a fixed seed so the fixture is
// reproducible. The production identity is a Workers secret and one file on one
// laptop, and it appears nowhere in this repository.
const SEED = Uint8Array.from({ length: 32 }, (_, index) => (index * 7 + 11) % 251);

const DEVICE = "0123456789abcdef0123456789abcdef";
const EMAIL = "parity@example.com";
const ISSUED = 1767225600; // 2026-01-01T00:00:00Z
const TRIAL_EXPIRES = ISSUED + 14 * 86400;
const ANNUAL_EXPIRES = ISSUED + 365 * 86400;

const KEYS = [
  { kind: "trial", id: "11111111-1111-4111-8111-111111111111", issued: ISSUED, expires: TRIAL_EXPIRES },
  { kind: "annual", id: "22222222-2222-4222-8222-222222222222", issued: ISSUED, expires: ANNUAL_EXPIRES },
  { kind: "lifetime", id: "33333333-3333-4333-8333-333333333333", issued: ISSUED },
];

export async function buildFixture() {
  const { privateBase64, publicBase64 } = keypairFromSeed(SEED);
  const signingKey = await importSigningKey(privateBase64);

  const keys = [];
  for (const spec of KEYS) {
    const token = await issueToken({ ...spec, device: DEVICE, email: EMAIL }, signingKey);
    keys.push({ ...spec, token });
  }

  return {
    note:
      "Generated by Service/tools/parity-fixture.mjs. These keys are signed by a fixed " +
      "throwaway seed, not by the production authority, and they unlock nothing. " +
      "ActivationServiceParityTests reads them through the shipping LicenseKey.verify.",
    device: DEVICE,
    email: EMAIL,
    publicKeyBase64: publicBase64,
    keys,
  };
}

function serialize(fixture) {
  return `${JSON.stringify(fixture, null, 2)}\n`;
}

const defaultPath = fileURLToPath(new URL("../fixtures/parity.json", import.meta.url));

// Compared as paths rather than as URLs: a repository checked out under a
// directory with a space in its name encodes differently on the two sides.
if (process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  const outIndex = process.argv.indexOf("--out");
  const path = outIndex >= 0 ? process.argv[outIndex + 1] : defaultPath;
  const text = serialize(await buildFixture());

  if (process.argv.includes("--check")) {
    const committed = readFileSync(defaultPath, "utf8");
    if (committed !== text) {
      console.error("parity fixture is stale: run `npm run fixture` in Service/ and commit the result");
      process.exit(1);
    }
    console.log("parity fixture is current");
  } else {
    writeFileSync(path, text);
    console.log(`wrote ${path}`);
  }
}
